train:
  _target_: torch.utils.data.DataLoader
  batch_size: 30
  num_workers: 2
  pin_memory: true
  shuffle: true
  drop_last: true
  worker_init_fn:
    _target_: hydra.utils.get_method
    path: src.utils.init.set_worker_seed
  collate_fn:
    _target_: hydra.utils.get_method
    path: src.dataset.collate.collate_fn

val:
  _target_: torch.utils.data.DataLoader
  batch_size: 30
  num_workers: 2
  pin_memory: true
  shuffle: false
  drop_last: false
  worker_init_fn:
    _target_: hydra.utils.get_method
    path: src.utils.init.set_worker_seed
  collate_fn:
    _target_: hydra.utils.get_method
    path: src.dataset.collate.collate_fn
